_BASE_: "Base-CenterMask-ResNet.yaml"

OUTPUT_DIR: "output/R101_ytvis"

MODEL:
  RESNETS:
    DEPTH: 101
  GNN:
    MP_ITERS: 1
  MATCHER:
    COEF: [ 1.25 , 1.0, 2.5, 10. ] # v9
  WEIGHTS: "checkpoints/R101_final.pth"
  RESFUSER:
    IS_ON : True

SOLVER:
  CHECKPOINT_PERIOD: 5000
  IMS_PER_BATCH: 2
  BASE_LR: 0.0005  # Note that RetinaNet uses a different default learning rate
  STEPS: (100000, 150000)
  MAX_ITER: 180000
  WARMUP_ITERS: 1000

DATASETS:
  PADDED_SAMPLING: True

MASKGNN:
  SCORE_THRESH_TEST: 0.05
  NODE_REP:
    FRAME1_SRC: "proposal"
